Special security announcement may
wso2/docs-security pull request #47
Opened 2023-05-10 11:23 UTC by anjai94

Adding following advisory into the documentation page.  

- WSO2-2022-2177
- WSO2-2022-2182

2023-05-10 11:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-security?pullRequest=47) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-security?pullRequest=47) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-security?pullRequest=47) it.</sub>

2023-05-15 13:06 UTC, 1uffyD9 requested changes
Have suggested few changes.

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2023.md
> +access multiple client applications.
Remove the line break

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2023.md
> +access multiple client applications.
Check the remaining contents as well

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +    WSO2 proactively issues security patches for all the supported product versions listed under WSO2 [Support Matrix](https://wso2.com/products/support-matrix/) ("available" and "deprecated" status)
Instead of 
```"available" and "deprecated" status```

shall we use,

```**available** and **deprecated** status```

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +When the notification based password recovery is enabled [1][2], A malicious actor could manipulate the REST API path and bypass authentication checks relevant to some Rest APIs.
```enabled [1][2]``` should be change to ```enabled [^1][^2]```

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +#### For below listed products, it is reoccomand to append the following configuration lines to the "&lt;PRODUCT-HOME&gt;/repository/conf/deployment.toml" file and restart the server.
```"&lt;PRODUCT-HOME&gt;/repository/conf/deployment.toml"```

change to,

``` `<PRODUCT-HOME/repository/conf/deployment.toml` ```

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +#### For below listed products, it is reoccomand to append the following configuration lines to the "&lt;PRODUCT-HOME&gt;/repository/conf/deployment.toml" file and restart the server.
Shall we change

```
#### For below listed products, it is reoccomand to append the following configuration lines to the
```

to,
```
#### Group 1:
For below listed products, it is recommend to append the following configuration lines to the
```

Please note that there's a spelling mistake, `recommend`.

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +<ul>
Let's change the list to markdown format,

```
* WSO2 Identity Server 5.9.0, 5.10.0, 5.11.0, 6.0.0
* WSO2 Identity Server as Key Manager 5.9.0, 5.10.0
* WSO2 API Manager 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.1.0
* WSO2 Open Banking AM 2.0.0, 3.0.0
* WSO2 Open Banking IAM 2.0.0, 3.0.0
```

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +```json
let's change `json` to `toml`

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +If you have already applied the similar configuration in your deployment.toml, you can add the above given configuration as a new config & restart the server.
let's enclose, `deployment.toml` with back quotes.

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +Add the following line as the first entry of the "&lt;ResourceAccessControl&gt;" tag of  "&lt;PRODUCT-HOME&gt;/repository/conf/identity/identity.xml" file and restart the server:
Feels like line 124 contains the same instruction. WDYT?

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +#### For remaing below listed products, please Add the following line as the first entry of the "&lt;ResourceAccessControl&gt;" tag of  "&lt;PRODUCT-HOME&gt;/repository/conf/identity/identity.xml" fi
Same as previous group.

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +WSO2 thanks, **[Rick Roane](https://www.linkedin.com/in/rick-r/)** for responsibly reporting the identified issue and working with us as we addressed it.
Shall we remove the bold format from the link?

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +
Let's change, 
```
[^1] [https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/ ](https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/)<br>
[^2] [https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery ](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery) <br>
[^3] [https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/ ](https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/)
```
to,

```
### References
[^1]: [https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/ ](https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/)
[^2]: [https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery ](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery)
[^3]: [https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/ ](https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/)
```

2023-05-15 13:06 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +WSO2 thanks, **[Rick Roane](https://www.linkedin.com/in/rick-r/)** for responsibly reporting the identified issue and working with us as we addressed it.
Let's check the same for other contents.

2023-05-16 14:56 UTC, 1uffyD9 requested changes
Added few suggestions.

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2101.md
> +* Add the following configuration to deployment.toml file.
```suggestion
* Add the following configuration to `deployment.toml` file.
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2101.md
> +    `[event.default_listener.governance_identity_store] enable_hybrid_data_store = false`
```suggestion
    ```toml
    [event.default_listener.governance_identity_store] enable_hybrid_data_store = false
    ```
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +
```suggestion
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Identity Server 5.9.0, 5.10.0, 5.11.0, 6.0.0
```suggestion
* WSO2 Identity Server 5.9.0, 5.10.0, 5.11.0, 6.0.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Identity Server as Key Manager 5.9.0, 5.10.0
```suggestion
* WSO2 Identity Server as Key Manager 5.9.0, 5.10.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 API Manager 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.1.0
```suggestion
* WSO2 API Manager 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.1.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Open Banking AM 2.0.0, 3.0.0
```suggestion
* WSO2 Open Banking AM 2.0.0, 3.0.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Open Banking IAM 2.0.0, 3.0.0
```suggestion
* WSO2 Open Banking IAM 2.0.0, 3.0.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +If you have already applied the similar configuration in your "deployment.toml", you can add the above given configuration as a new config & restart the server.
```suggestion
If you have already applied the similar configuration in your `deployment.toml`, you can add the above given configuration as a new config & restart the server.
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +For group 2 products, please Add the below given config as the first entry of the `<ResourceAccessControl>` tag of "`<PRODUCT-HOME>`/repository/conf/identity/identity.xml" file and restart the server
```suggestion
For group 2 products, please Add the below given config as the first entry of the `<ResourceAccessControl>` tag of `<PRODUCT-HOME>/repository/conf/identity/identity.xml` file and restart the server.
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Identity Server 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0
```suggestion
* WSO2 Identity Server 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Identity Server as Key Manager 5.3.0, 5.5.0, 5.6.0, 5.7.0
```suggestion
* WSO2 Identity Server as Key Manager 5.3.0, 5.5.0, 5.6.0, 5.7.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Open Banking AM 1.3.0, 1.4.0, 1.5.0
```suggestion
* WSO2 Open Banking AM 1.3.0, 1.4.0, 1.5.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +- WSO2 Open Banking IAM 1.3.0, 1.4.0, 1.5.0
```suggestion
* WSO2 Open Banking IAM 1.3.0, 1.4.0, 1.5.0
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +Example:
Shall we use the example code segment like this? 

```suggestion
!!! example
     ```xml
      <ResourceAccessControl>
          <Resource context="(.*)/((\.+)|(.*;+.*)|%2e)/(.*)" secured="true" http-method="all">
                 <Permissions>/</Permissions>
          </Resource>
          <Resource context="(.*)" secured="false" http-method="OPTIONS"/>
          <Resource context="/" secured="false" http-method="GET"/>
          ......
      </ResourceAccessControl>
      ```
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +WSO2 thanks, **[Rick Roane]**(https://www.linkedin.com/in/rick-r/) for responsibly reporting the identified issue and working with us as we addressed it.
```suggestion
WSO2 thanks, [Rick Roane](https://www.linkedin.com/in/rick-r/) for responsibly reporting the identified issue and working with us as we addressed it.
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2182.md
> +- [https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1603](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1603)
```suggestion
* [https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1603](https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1603) 
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2182.md
> +
```suggestion
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2357.md
> +* If the application does not support the maintenance of multiple secrets, then create a new application. Once the new application is created, Then update the client id and client secret of the confi
```suggestion
* If the application does not support the maintenance of multiple secrets, then create a new application. Once the new application is created, then update the client id and client secret of the configured IDP in the environment. And then delete the old application.
```

2023-05-16 14:56 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2023-2447.md
> +WSO2 thanks, **[Tom O’Neill](https://www.linkedin.com/in/the-tom-oneill)** for responsibly reporting the identified issue and working with us as we addressed it.
```suggestion
WSO2 thanks, [Tom O’Neill](https://www.linkedin.com/in/the-tom-oneill) for responsibly reporting the identified issue and working with us as we addressed it.
```

2023-05-18 07:52 UTC, 1uffyD9 submitted a review, later dismissed

2023-06-15 14:26 UTC, anjai94 commented
Will send the new PR.

2023-06-15 14:26 UTC, closed without merging