Public Announcement - June
wso2/docs-security pull request #50
Opened 2023-06-15 15:44 UTC by anjai94

Following security advisory will be added vi this PR.
- WSO2-2022-2177
- WSO2-2022-2023
- WSO2-2022-2101
- WSO2-2022-2182
- WSO2-2023-2447

2023-06-15 15:59 UTC, 1uffyD9 requested changes
Suggested few changes.

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/2023-advisories.md
> +* [WSO2-2022-1821]({{#base_path#}}/security-announcements/security-advisories/2023/WSO2-2022-1821/)
```suggestion
* [WSO2-2022-1821]({{#base_path#}}/security-announcements/security-advisories/2023/WSO2-2022-1821)
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/2023-advisories.md
>  * [WSO2-2022-1910]({{#base_path#}}/security-announcements/security-advisories/2023/WSO2-2022-1910/)
```suggestion
* [WSO2-2022-1910]({{#base_path#}}/security-announcements/security-advisories/2023/WSO2-2022-1910)
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2101.md
> +* Add the following configuration to deployment.toml file.
```suggestion
* Add the following configuration to `deployment.toml` file.
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2101.md
> +    `[event.default_listener.governance_identity_store] enable_hybrid_data_store = false`
```suggestion
    ```toml
    [event.default_listener.governance_identity_store] enable_hybrid_data_store = false
    ```
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +For below listed products, it is recommend to append the following configuration lines to the `&lt;PRODUCT-HOME&gt;/repository/conf/deployment.toml` file and restart the server.
```suggestion
For below listed products, it is recommend to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deployment.toml` file and restart the server.
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +[^1]: [https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/ ](https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/)
```suggestion
[^1]: [https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/](https://is.docs.wso2.com/en/latest/guides/password-mgt/recover-password/)
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +[^2]: [https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery ](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/
```suggestion
[^2]: [https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/security/user-account-management/#enable-password-recovery)
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +[^3]: [https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/ ](https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/)
```suggestion
[^3]: [https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/](https://ob.docs.wso2.com/en/latest/get-started/set-up-accelerators/)
```

2023-06-15 15:59 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2357.md
> +* If the application does not support the maintenance of multiple secrets, then create a new application. Once the new application is created, Then update the client id and client secret of the confi
```suggestion
* If the application does not support the maintenance of multiple secrets, then create a new application. Once the new application is created, then update the client id and client secret of the configured IDP in the environment. Then delete the old application.
```

2023-06-16 04:58 UTC, ayomawdb commented on en/mkdocs.yml
> +        - 'WSO2-2023-2617': 'security-announcements/security-advisories/2023/WSO2-2022-2617.md'
This line should be removed

2023-06-16 04:58 UTC, ayomawdb commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2182.md
> +cvss: "CVSS Score:  8.3 (CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:L)"
```suggestion
cvss: "8.3 (CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:L)"
```

2023-06-16 04:58 UTC, ayomawdb commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +<p class="doc-info">9.4 (CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L)</p>
```suggestion
<p class="doc-info">CVSS Score: 9.4 (CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L)</p>
```

2023-06-16 16:57 UTC, ayomawdb approved these changes

2023-06-19 03:58 UTC, 1uffyD9 approved these changes

2023-06-19 08:12 UTC, merged