Adding temporary mitigation steps for WSO2-2021-1738.
wso2/docs-security pull request #52
Opened 2023-07-12 08:09 UTC by anjai94

2023-07-28 09:41 UTC, ayomawdb submitted a review, later dismissed

2023-08-02 06:25 UTC, 1uffyD9 requested changes
Suggested few changes.

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +context="(.*)/fileupload(.*)"
```suggestion
context="(.*)/fileupload/(.*)"
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +For following **WSO2 API Manager version 4.0.0, 3.2.0, 3.1.0 and 3.0.0**, it is recommand to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deployment.toml` file and
```suggestion
For below listed product versions, it is recommended to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deployment.toml` file and restart the server.

* WSO2 API Manager version 4.0.0, 3.2.0, 3.1.0 and 3.0.0
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +For below listed WSO2 Identity Server and Identity Server As Key Manager product versions, it is recommend to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deploymen
```suggestion
For below listed product versions, it is recommended to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deployment.toml` file and restart the server.
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
* WSO2 Open Banking IAM 2.0.0

```

Because the [old docs page](https://wso2docs.atlassian.net/wiki/spaces/Security/pages/31426027/Security+Advisory+WSO2-2021-1738) contains ob versions as well.

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +For following **WSO2 Enterprise Integrator version 6.6.0, 6.5.0, 6.4.0, 6.3.0, and 6.2.0**, it is recommand to remove the following mappings in the <product_home>/conf/carbon.xml file from the <FileU
```suggestion
For below listed product versions, it is recommended to remove the following mappings in the `<PRODUCT-HOME>/conf/carbon.xml` file from the `<FileUploadConfig>` section.

* WSO2 Enterprise Integrator version 6.6.0, 6.5.0, 6.4.0, 6.3.0, 6.2.0 and older versions
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +For Business process / Broker and Analytics profiles apply the same change for carbon.xml file at the following locations respectively.
```suggestion
For Business process / Broker and Analytics profiles apply the same change for **carbon.xml** file at the following locations respectively.
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +* <product_home>/wso2/broker/conf/carbon.xml
```suggestion
* `<PRODUCT-HOME>/wso2/broker/conf/carbon.xml`
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +* <product_home>/wso2/business-process/conf/carbon.xml
```suggestion
* `<PRODUCT-HOME>/wso2/business-process/conf/carbon.xml`
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +* <product_home>/wso2/analytics/conf/carbon.xml
```suggestion
* `<PRODUCT-HOME>/wso2/analytics/conf/carbon.xml`
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
```suggestion

#### GROUP 1
For below listed product versions, it is recommended to remove all the mappings defined inside the `FileUploadConfig` tag in `<PRODUCT-HOME>/repository/conf/carbon.xml`.

* WSO2 API Manager 2.6.0, 2.5.0, 2.2.0, and older versions
* WSO2 Identity Server 5.8.0, 5.7.0, 5.6.0, 5.5.0, 5.4.1, 5.4.0, 5.3.0, 5.2.0, and older versions
* WSO2 Identity Server as Key Manager 5.7.0, 5.6.0, 5.5.0, 5.3.0, and older versions
* WSO2 IS Analytics 5.6.0, 5.5.0, 5.4.1, 5.4.0, and older versions
* WSO2 OBAM 1.5.0 and older versions
* WSO2 OBKM 1.5.0 and older versions


```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 1:
```suggestion
#### GROUP 2
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
````suggestion

#### GROUP 3
For below listed product versions, it is recommended to add the following configuration to `<PRODUCT-HOME>/repository/conf/deployment.toml`

```xml
[[resource.access_control]]
context="(.*)/fileupload/csv(.*)"
secure=false
http_method = "all"
 
[[resource.access_control]]
context="(.*)/fileupload/resource(.*)"
secure=false
http_method = "all"
 
[[resource.access_control]]
context="(.*)/fileupload/(.*)"
secure=true
http_method = "all"
permissions = ["/permission/protected/"]
```
````

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 2:
```suggestion
#### GROUP 4
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 3:
```suggestion
#### GROUP 5
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 4:
```suggestion
#### GROUP 6
Other unsupported products/versions based on WSO2 Carbon Kernel 4 versions, it is recommended to remove all the mappings defined inside the `FileUploadConfig` tag in `<PRODUCT-HOME>/repository/conf/carbon.xml`.
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +FOR following WSO2 API Manager versions 2.6.0, 2.5.0, 2.2.0,
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +It is recommand to Remove the following resource entry under <ResourceAccessControl> in the <product_home>/repository/conf/identity/identity.xml.
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```toml
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload(.*)" secured="false" http-method="all"/>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +And, add the following entries under <ResourceAccessControl>.
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```toml
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload/resource(.*)" secured="false" http-method="all"/>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload(.*)" secured="true" http-method="all">
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +  <Permissions>/permission/protected/</Permissions>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +</Resource>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +Further, we highly encourage to Remove all the mappings defined inside the FileUploadConfig tag in <product_home>/repository/conf/carbon.xml.
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 5:
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +* WSO2 Identity Server 5.8.0, 5.7.0, 5.6.0, 5.5.0, 5.4.1, 5.4.0, 5.3.0
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +* WSO2 Identity Server as Key Manager 5.7.0, 5.6.0, 5.5.0, 5.3.0
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +Remove the following resource entry under <ResourceAccessControl> in the <product_home>/repository/conf/identity/identity.xml
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```toml
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload(.*)" secured="false" http-method="all"/>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +And, add the following entries under <ResourceAccessControl>,
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```toml
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload/service(.*)" secured="false" http-method="all"/>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload/entitlement-policy(.*)" secured="false" http-method="all"/>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload/resource(.*)" secured="false" http-method="all"/>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +<Resource context="(.*)/fileupload(.*)" secured="true" http-method="all">
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +  <Permissions>/permission/protected/</Permissions>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +</Resource>
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 6:
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +* WSO2 Identity Server 5.2.0
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +* WSO2 IS Analytics 5.4.0, 5.4.1, 5.5.0 5.6.0
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +It is recommand to remove all the mappings defined inside the c tag in <product_home>/repository/conf/carbon.xml
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +```
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2055.md
> +"/permission/admin/manage/event-publish" permission.
```suggestion
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2055.md
> +XML external entity (XXE) vulnerability is possible through SOAP API when the malicious actor is provided with
```suggestion
XML external entity (XXE) vulnerability is possible through SOAP API when the malicious actor is provided with **/permission/admin/manage/event-publish** permission.
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +# SECURITY ADVISORY WSO2-2022-2177
```suggestion
# Security Advisory WSO2-2022-2177
```
Let's follow the existing format and make revert the change here.

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +#### GROUP 1:
```suggestion
#### GROUP 1
```

2023-08-02 06:25 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-2177.md
> +#### GROUP 2:
```suggestion
#### GROUP 2
```

2023-08-02 06:25 UTC, 1uffyD9 requested changes
Suggested few changes.

2023-08-02 08:19 UTC, ayomawdb approved these changes

2023-08-02 08:20 UTC, merged