Update product versions in Secure Product Deployment
wso2/docs-security pull request #55
Opened 2023-08-02 12:04 UTC by anjai94

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2023-08-09 03:46 UTC, 1uffyD9 approved these changes
Added a small suggestion.

2023-08-09 03:46 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-1745.md
> +# SECURITY ADVISORY WSO2-2022-1745
```suggestion
# Security Advisory WSO2-2022-1745
```

2023-10-03 12:01 UTC, 1uffyD9 approved these changes
+1 to proceed once the comment has been addressed.

2023-10-03 12:01 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-1745.md
> +
Are we going to mention the public PR?

2023-10-03 12:03 UTC, anjai94 commented on en/docs/security-announcements/security-advisories/2023/WSO2-2022-1745.md
> +
Yes this is current process. We can not provide public PR for non master fixes.

2023-10-16 05:28 UTC, 1uffyD9 requested changes

2023-10-16 05:28 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/.gitignore
We can add this to base `.gitignore` file.

2023-10-16 05:28 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/2023-advisories.md
> +* [WSO2-2022-1745]({{#base_path#}}/security-announcements/security-advisories/2023/WSO2-2022-1745)
check this.

2023-10-16 05:28 UTC, 1uffyD9 commented on en/docs/security-reporting/reward-and-acknowledgement-program/hall-of-fame.md
> +| [Avinash Jain](https://www.linkedin.com/in/avinash-jain-54524678/) |
Shall we move this under ```2023 -> WSO2 Products and Infrastructure```.

2023-10-16 05:28 UTC, 1uffyD9 commented on en/docs/security-reporting/reward-and-acknowledgement-program/hall-of-fame.md
> +| [Shailendra Singh Sachan](https://www.linkedin.com/in/shailendra-singh-sachan-b8205b184)
Shall we move this under ```2023 -> WSO2 Products and Infrastructure```.

2023-10-16 05:28 UTC, 1uffyD9 commented on en/docs/security-reporting/reward-and-acknowledgement-program/hall-of-fame.md
> +| [Suraj Theekshana](https://www.linkedin.com/in/suraj-theekshana-10171023a/)
Shall we move this under ```2023 -> WSO2 Products and Infrastructure```.

2023-10-16 05:28 UTC, 1uffyD9 commented on en/mkdocs.yml
> +        - 'WSO2-2022-1745': 'security-announcements/security-advisories/2023/WSO2-2022-1745.md'
This one is already in `2022` page.

2023-11-01 06:32 UTC, 1uffyD9 requested changes
have one place to check and change (if required).

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
>  * WSO2 Open Banking KM 1.4.0, up to 2.0.0
```suggestion
* WSO2 Open Banking KM 1.4.0, up to 1.5.0
* WSO2 Open Banking IAM 2.0.0
```

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
>  | WSO2 Identity Server                |          5.11.0 |          106 |           N/A |
```suggestion
| WSO2 Identity Server                |          5.11.0 |          103 |           N/A |
```

should be corrected as 103

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
>  | WSO2 Identity Server                |          5.11.0 |          106 |           N/A |
Also,

WSO2 Enterprise Integrator	6.4.0	`58` should be corrected as `74`
WSO2 Open Banking AM	2.0.0	`119`	should be corrected as `118`
WSO2 Open Banking IAM	2.0.0	`127`	should be corrected as `126`

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> -For below listed product versions, it is recommended to remove all the mappings defined inside the `FileUploadConfig` tag in `<PRODUCT-HOME>/repository/conf/carbon.xml`.
Why are we removing these configs?

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
>  For following **WSO2 API Manager version 4.0.0, 3.2.0, 3.1.0 and 3.0.0**, it is recommand to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deployment.toml` file and
```suggestion
For below listed product versions, it is recommand to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deployment.toml` file and restart the server.

* WSO2 API Manager version 4.0.0, 3.2.0, 3.1.0 and 3.0.0 
```

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 2
```suggestion
#### GROUP 3
```

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 3
```suggestion
#### GROUP 4
```

2023-11-01 06:32 UTC, 1uffyD9 commented on en/get-pip.py
Should be removed

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> -For below listed product versions, it is recommended to remove all the mappings defined inside the `FileUploadConfig` tag in `<PRODUCT-HOME>/repository/conf/carbon.xml`.
resolved

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
>  For following **WSO2 API Manager version 4.0.0, 3.2.0, 3.1.0 and 3.0.0**, it is recommand to append the following configuration lines to the `<PRODUCT-HOME>/repository/conf/deployment.toml` file and
resolved

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 2
resolved

2023-11-01 06:32 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2022/WSO2-2021-1738.md
> +#### GROUP 3
resolved

2023-11-01 06:33 UTC, 1uffyD9 commented on en/get-pip.py
resolved

2023-11-01 06:35 UTC, 1uffyD9 requested changes

2023-11-01 06:35 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2023/2023-advisories.md
> +* [WSO2-2022-1745]({{#base_path#}}/security-announcements/security-advisories/2023/WSO2-2022-1745)
This advisory is in 2022 advisory list. please check

2023-11-01 07:35 UTC, 1uffyD9 approved these changes
Contents look good. +1

2023-11-02 06:56 UTC, 1uffyD9 approved these changes

2023-11-03 05:07 UTC, ayomawdb approved these changes

2023-11-03 05:07 UTC, merged