Public announcement April - 2024
wso2/docs-security pull request #61
Opened 2024-04-21 11:01 UTC by anjai94

Following advisory will be announced via this PR. 
- WSO2-2022-1754
- WSO2-2022-1988
- WSO2-2022-2049
- WSO2-2022-2165
- WSO2-2022-2203
- WSO2-2022-2208
- WSO2-2022-2254
- WSO2-2023-2075
- WSO2-2023-2308
- WSO2-2023-2577
- WSO2-2023-2626
- WSO2-2023-2831
- WSO2-2023-2935

2024-04-21 11:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-security?pullRequest=61) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-security?pullRequest=61) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-security?pullRequest=61) it.</sub>

2024-06-03 06:00 UTC, 1uffyD9 requested changes
Added few comments. 

Additionally for following advisories, public PRs are missing,

- WSO2-2022-1754
- WSO2-2022-1988

Also, I noted one more different content in the `WSO2-2022-2203` advisory. Could you please check the content against the PMT.

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-1754.md
> +published: April 20, 2024
@anjai94 should we change this date?

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +published: October 28, 2023
@anjai94 is this `published` date correct?

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +- &lt;PRODUCT_HOME&gt;/repository/deployment/server/webapps/authenticationendpoint/EndpointConfig.properties
We can escape the html tag like following,

```suggestion
- <PRODUCT_HOME\>/repository/deployment/server/webapps/authenticationendpoint/EndpointConfig.properties
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +- &lt;PRODUCT_HOME&gt;/repository/deployment/server/webapps/accountrecoveryendpoint
```suggestion
- <PRODUCT_HOME\>/repository/deployment/server/webapps/accountrecoveryendpoint/RecoveryEndpointConfig.properties
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +  /RecoveryEndpointConfig.properties
I guess we don't need this line,

```suggestion

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +In the default deployment mode where authenticationendpoint & accountrecoveryendpoint portals are hosted within the Identity Server itself, the default REST API password could be exposed through the
Small suggestions to make it more readable,

```suggestion
In the default deployment mode where **authenticationendpoint** & **accountrecoveryendpoint** portals are hosted within the Identity Server itself, the default REST API password could be exposed through the `.properties` files in the root folder. But WSO2 has strongly recommended through deployment security guidelines to change the default REST API passwords [1] (step 2 - first 2 points). The modification is made through the `deployment.toml`. This will only change the config file inside the `<PRODUCT_HOME>/repository/conf` folder, and will not alter the file in question. Hence a malicious actor will not be able to get hold of modified passwords. In summary, if you have already changed the default REST API password, and have done it through deployment. The toml REST API credentials are not exposed.
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +- webapps/authenticationendpoint/EndpointConfig.properties
```suggestion
- `webapps/authenticationendpoint/EndpointConfig.properties`
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +- webapps/accountrecoveryendpoint/RecoveryEndpointConfig.properties
```suggestion
- `webapps/accountrecoveryendpoint/RecoveryEndpointConfig.properties`
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +In deployments where the changed credential was exposed, it is further recommended to search your access logs for entries with "EndpointConfig.properties" and "RecoveryEndpointConfig.properties" to c
```suggestion
In deployments where the changed credential was exposed, it is further recommended to search your access logs for entries with `EndpointConfig.properties` and `RecoveryEndpointConfig.properties` to confirm if an external party has accessed these configuration files.
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2208.md
> +When "validating JWTs generated by external OAuth providers" [1], if JWKS endpoint call fails due to a network issue, or returns an unexpected response, the JWT token is considered to be valid.
Maybe this might improve the readability, 
```suggestion
When **validating JWTs generated by external OAuth providers** [^1], if JWKS endpoint call fails due to a network issue, or returns an unexpected response, the JWT token is considered to be valid.
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2208.md
> +
```suggestion

### References
[^1]: [https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/access-token-types/jwt-tokens/#validating-jwts-generated-by-external-oauth-providers](https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/access-token-types/jwt-tokens/#validating-jwts-generated-by-external-oauth-providers)

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2208.md
> +[1] [https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/access-token-types/jwt-toke
We can remove this and have references like suggested after line 45.
```suggestion

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2208.md
> +ns/#validating-jwts-generated-by-external-oauth-providers](https://apim.docs.wso2.com/en/latest/design/api-security/oauth2/access-token-types/jwt-tokens/#validating-jwts-generated-by-external-oauth-p
```suggestion

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2208.md
> +This vulnerability only affected deployments that use JWTs generated by external OAuth providers to authenticate APIs. Since the JWT token is considered to be valid when the specific condition highli
```suggestion
This vulnerability only affected deployments that use JWTs generated by external OAuth providers to authenticate APIs. Since the JWT token is considered to be valid when the specific condition highlighted in the [Description](#description) is met, the backend call is made without doing the signature validation.
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +    **If you are a WSO2 customer with Support Subscription, please use [WSO2 Updates](https://wso2.com/updates/) in order to apply the fix.**
```suggestion
    **If you are a WSO2 customer with Support Subscription, please use [WSO2 Updates](https://wso2.com/updates/) in order to apply the fix.**
    

### References
[^1]: [https://is.docs.wso2.com/en/latest/deploy/security/product-level-security-guidelines/#configure-client-authentication](https://is.docs.wso2.com/en/latest/deploy/security/product-level-security-guidelines/#configure-client-authentication)

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-1988.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2049.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +published: October 28, 2023
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2203.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2208.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2254.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2075.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2308.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2577.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2831.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2935.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2938.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2988.md
> +published: April 20, 2024
```suggestion
published: May 31, 2024
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2577.md
> +[1] [https://is.docs.wso2.com/en/latest/deploy/configure-recaptcha/#](https://is.docs.wso2.com/en/latest/deploy/configure-recaptcha/#)
```suggestion

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2577.md
> +Product provided reCaptcha [1] validation to prevent possibility of username enumeration. Even when reCaptcha validation is enabled, due to the absence of a validation in the check available username
```suggestion
Product provided reCaptcha [^1] validation to prevent possibility of username enumeration. Even when reCaptcha validation is enabled, due to the absence of a validation in the check available username feature executed during the self-registration flow, a malicious actor could exploit this feature and harvest information about users who have already registered.
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2577.md
> +    **If you are a WSO2 customer with Support Subscription, please use [WSO2 Updates](https://wso2.com/updates/) in order to apply the fix.**
```suggestion
    **If you are a WSO2 customer with Support Subscription, please use [WSO2 Updates](https://wso2.com/updates/) in order to apply the fix.**
    

### References
[^1]: [https://is.docs.wso2.com/en/latest/deploy/configure-recaptcha/#](https://is.docs.wso2.com/en/latest/deploy/configure-recaptcha/#)
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +    Identity Provider -> Resident -> Account Management -> Account Recovery -> Recovery callback URL regex: regexp=(https://((example1.com)|(example2:port))/.*)
```suggestion
    Identity Provider -> Resident -> Account Management -> Account Recovery -> Recovery callback URL regex: 
    
    ```
    regexp=(https://((example1.com)|(example2:port))/.*)
    ```
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +    Identity Provider -> Resident -> User Onboarding-> Self Registration -> User self registration callback URL regex: regexp=(https://((example1.com)|(example2:port))/.*)
```suggestion
    Identity Provider -> Resident -> User Onboarding-> Self Registration -> User self registration callback URL regex: 
    
    ```
     regexp=(https://((example1.com)|(example2:port))/.*)
    ```
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +    Identity Provider -> Resident -> User Onboarding-> Lite User Registration -> Lite User registration callback URL regex: regexp=(https://((example1.com)|(example2:port))/.*)
```suggestion
    Identity Provider -> Resident -> User Onboarding-> Lite User Registration -> Lite User registration callback URL regex: 
    
    ```
    regexp=(https://((example1.com)|(example2:port))/.*)
    ```
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +
```suggestion


### References:
[^1]: [For WSO2 API Manager](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment/#runtime-level-security)
[^2]: [For WSO2 Identity Server](https://is.docs.wso2.com/en/5.11.0/administer/product-level-security-guidelines/)

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +Moreover, the product documentations are updated with the corrected configuration samples.
```suggestion
Moreover, the product documentations are updated with the corrected configuration samples[^1][^2].
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +* [For WSO2 API Manager](https://apim.docs.wso2.com/en/latest/install-and-setup/setup/deployment-best-practices/security-guidelines-for-production-deployment/#runtime-level-security)
```suggestion

```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +* [For WSO2 Identity Server](https://is.docs.wso2.com/en/5.11.0/administer/product-level-security-guidelines/)
```suggestion
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2831.md
> +### IMPACT
Better to remove the next line character in this section.

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2935.md
> +The recommended solution is to apply the provided patch/update to the affected versions of the products. If there are any instructions given with the patch/update, please make sure those are followed
```suggestion
The recommended solution is to apply the provided patch/update to the affected versions of the products. If there are any instructions given with the patch/update, please make sure those are followed properly. The fix will deliver the `X-Content-Type-Options: nosniff` header for error page responses, preventing browsers from performing content sniffing.
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2938.md
> +We have provided a sample configuration based on the use case where the mediation sequence requires usage of "java.util.ArrayList" class.
```suggestion
We have provided a sample configuration based on the use case where the mediation sequence requires usage of `java.util.ArrayList` class.
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2938.md
> +var s = new java.util.ArrayList();
```suggestion
  ```java
  var s = new java.util.ArrayList(); ```
```

2024-06-03 06:00 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2938.md
> +**Sample sequence code:**
Better to add this inside a java code block

2024-06-04 08:09 UTC, 1uffyD9 requested changes
Added few suggestions

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +[1] [https://is.docs.wso2.com/en/latest/deploy/security/product-level-security-guidelines/#configure-client-authentication](https://is.docs.wso2.com/en/latest/deploy/security/product-level-security-g
```suggestion

```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +In the default deployment mode where **authenticationendpoint** & **accountrecoveryendpoint** portals are hosted within the Identity Server itself, the default REST API password could be exposed thro
```suggestion
In the default deployment mode where **authenticationendpoint** & **accountrecoveryendpoint** portals are hosted within the Identity Server itself, the default REST API password could be exposed through the `.properties` files in the root folder. But WSO2 has strongly recommended through deployment security guidelines to change the default REST API passwords [^1] (step 2 - first 2 points). The modification is made through the `deployment.toml`. This will only change the config file inside the `<PRODUCT_HOME>/repository/conf` folder, and will not alter the file in question. Hence a malicious actor will not be able to get hold of modified passwords. In summary, if you have already changed the default REST API password, and have done it through deployment. The toml REST API credentials are not exposed.
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2254.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2208.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2203.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2165.md
> +<p class="doc-info">Published: October 28, 2023</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-2049.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2022-1988.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2075.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2308.md
> +published: May 31, 2024
```suggestion
published: May 31, 2024
severity: N/A
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2308.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: April 20, 2024</p>
<p class="doc-info">Severity: N/A</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2577.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2626.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2831.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2935.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2938.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 08:09 UTC, 1uffyD9 commented on en/docs/security-announcements/security-advisories/2024/WSO2-2023-2988.md
> +<p class="doc-info">Published: April 20, 2024</p>
```suggestion
<p class="doc-info">Published: May 31, 2024</p>
```

2024-06-04 10:22 UTC, 1uffyD9 approved these changes
+1 from my end.

2024-06-06 10:17 UTC, ayomawdb approved these changes

2024-06-06 10:18 UTC, merged