Add CVE justification for CVE-2022-45868
wso2/docs-security pull request #69
Opened 2024-08-05 20:32 UTC by anjai94

2024-08-05 20:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-security?pullRequest=69) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-security?pullRequest=69) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-security?pullRequest=69) it.</sub>

2024-08-06 00:39 UTC, 1uffyD9 requested changes

2024-08-06 00:39 UTC, 1uffyD9 commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +The web-based admin console in H2 Database Engine before 2.2.220 can be started via the CLI with the argument -webAdminPassword, which allows the user to specify the password in cleartext for the web
```suggestion
The web-based admin console in H2 Database Engine before 2.2.220 can be started via the CLI with the argument `-webAdminPassword`, which allows the user to specify the password in cleartext for the web admin console. Therefore, a local user is able to access the password by listing the processes and their arguments [^1].
```

2024-08-06 00:39 UTC, 1uffyD9 commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +Furthermore, the CVE-2022-45868 is a disputed vulnerability since the vendor states that "This is not a vulnerability of H2 Console Passwords should never be passed on the command line and every qual
```suggestion
Furthermore, the CVE-2022-45868 is a disputed vulnerability since the vendor states that, 
> This is not a vulnerability of H2 Console Passwords should never be passed on the command line and every qualified DBA or system administrator is expected to know that.
```

2024-08-07 04:28 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +* WSO2 Open Banking AM : 2.0.0, 1.5.0, 1.4.0
```suggestion
* WSO2 Open Banking AM : 2.0.0, 1.5.0, 1.4.0
* Any other WSO2 products containing the H2 database engine 
```

2024-08-07 04:28 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +In WSO2 API Manager the H2 web-based console is disabled by default and the deployment.toml configuration related feature to enable/disable the H2 web console is removed from APIM 4.2.0 onwards. More
```suggestion
The vulnerability is reported when starting the H2 web based console using the CLI with a clear text password which is not applicable for WSO2 products.

Furthermore, the H2 web based console is disabled by default, and newer WSO2 product versions including APIM 4.2.0 onwards even removes deployment.toml configuration option to enable/disable the H2 web console. 
```

2024-08-07 04:28 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +Furthermore, the CVE-2022-45868 is a disputed vulnerability since the vendor states that,
```suggestion
Furthermore, the [CVE-2022-45868](https://nvd.nist.gov/vuln/detail/CVE-2022-45868) is a disputed vulnerability and the project states the following: 
```

2024-08-07 04:28 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +* H2 console has been disabled by default and the configuration to enable the console is removed from APIM 4.2.0 onwards.
```suggestion
* H2 console has been disabled by default in WSO2 products.
* Vulnerability is reported when starting the H2 web based console using the CLI which is never applicable to WSO2 products.
* Upgrading to a H2 version that is not flagged for this vulnerability requires backward incompatible changes to the product. This requires users of WSO2 products to perform a data migration, when the vulnerability itself can never affect security of WSO2 products.
```

2024-08-07 04:28 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +* [CVE-2022-45868](https://nvd.nist.gov/vuln/detail/CVE-2022-45868) is reported for H2 database engine before 2.2.220
```suggestion
* [CVE-2022-45868](https://nvd.nist.gov/vuln/detail/CVE-2022-45868) is a disputed CVE.
```

2024-08-07 04:28 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +Therefore, this is not an exploitable vulnerability in WSO2 products.
```suggestion
Therefore, WSO2 concludes that this is not an exploitable vulnerability in WSO2 products, and an H2 update will not be performed due to [CVE-2022-45868](https://nvd.nist.gov/vuln/detail/CVE-2022-45868).
```

2024-08-07 04:37 UTC, 1uffyD9 requested changes
Added few suggestions

2024-08-07 04:37 UTC, 1uffyD9 commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +Furthermore, the CVE-2022-45868 is a disputed vulnerability since the vendor states that,
```suggestion
Furthermore, the CVE-2022-45868[^1] is a disputed vulnerability and the project states the following: 
```

2024-08-07 04:37 UTC, 1uffyD9 commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +* [CVE-2022-45868](https://nvd.nist.gov/vuln/detail/CVE-2022-45868) is reported for H2 database engine before 2.2.220
```suggestion
* CVE-2022-45868[^1] is a disputed CVE.
```

2024-08-07 04:37 UTC, 1uffyD9 commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-45868.md
> +Therefore, this is not an exploitable vulnerability in WSO2 products.
```suggestion
Therefore, WSO2 concludes that **this is not an exploitable vulnerability in WSO2 products**, and **an H2 update will not be performed due to CVE-2022-45868**[^1].
```

2024-08-08 04:14 UTC, ayomawdb approved these changes

2024-08-08 04:15 UTC, merged