Added justifications for CVE-2021-23463 and CVE-2022-23221
wso2/docs-security pull request #78
Opened 2024-10-30 11:17 UTC by tharikaGitHub

## Purpose
Please refer $subject.

2024-10-30 11:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2/docs-security?pullRequest=78) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2/docs-security?pullRequest=78) before we can accept your contribution.<br/><hr/>**Tharika Madurapperuma** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2/docs-security?pullRequest=78) it.</sub>

2024-10-31 03:54 UTC, ayomawdb approved these changes

2024-10-31 03:57 UTC, ayomawdb requested changes

2024-10-31 03:57 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2021-23463.md
> +Due to following key points,
```suggestion
```

2024-10-31 03:57 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-23221.md
> +Due to following key points,
```suggestion
```

2024-10-31 03:57 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-23221.md
> +
```suggestion
```

2024-10-31 03:57 UTC, ayomawdb commented on en/docs/security-announcements/cve-justifications/2024/CVE-2021-23463.md
> +
```suggestion
```

2024-10-31 13:00 UTC, tharikaGitHub commented on en/docs/security-announcements/cve-justifications/2024/CVE-2021-23463.md
> +Due to following key points,
Fixed with https://github.com/wso2/docs-security/pull/78/commits/ca6be2eae75717337bc2c5379dd631c6f10af904

2024-10-31 13:00 UTC, tharikaGitHub commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-23221.md
> +Due to following key points,
Fixed with https://github.com/wso2/docs-security/pull/78/commits/ca6be2eae75717337bc2c5379dd631c6f10af904

2024-10-31 13:00 UTC, tharikaGitHub commented on en/docs/security-announcements/cve-justifications/2024/CVE-2022-23221.md
> +
Fixed with https://github.com/wso2/docs-security/pull/78/commits/ca6be2eae75717337bc2c5379dd631c6f10af904

2024-10-31 13:00 UTC, tharikaGitHub commented on en/docs/security-announcements/cve-justifications/2024/CVE-2021-23463.md
> +
Fixed with https://github.com/wso2/docs-security/pull/78/commits/ca6be2eae75717337bc2c5379dd631c6f10af904

2024-11-01 03:50 UTC, ayomawdb approved these changes

2024-11-01 03:51 UTC, ayomawdb commented
@miyuru @nandika Could you also approve the PR, so that we can publish this.

2024-11-01 11:24 UTC, nandika approved these changes

2024-11-03 13:04 UTC, miyuru approved these changes

2024-11-04 06:37 UTC, merged